### ISSUE TITLE
API's business not working

### ISSUE THREAD

**Issue by jecarlos14** [IDMONEY/MoneyMakingWalletBK#5]
**Describe the bug**
Search business operation is not working as expexted

**To Reproduce**
1. Run the application
2. Open the browser and go to api/business/search
3. See error

**Expected behavior**
System must return a list of businesses related to the name

**Additional context**
System must have a  filtering url for collections.
Suggested URL: api/business?name=

**Comment by nekramste** [comment]
Already noted. Some usefull information is available [here](https://blog.mwaysolutions.com/2014/06/05/10-best-practices-for-better-restful-api/)

Thank you.

**Comment by nekramste** [comment]
Thanks @jecarlos14 . I have made the suggested changes to the API
