### ISSUE TITLE
I can´t log in

### ISSUE THREAD

**Issue by jecarlos14** [IDMONEY/MoneyMakingWalletBK#6]
**Describe the bug**
I can´t log in with app

**To Reproduce**
1. Open to the app
2. Typed my user and password
3. Click in the button 'Login'
4. The system show me 'Email or password is incorrect'

**Expected behavior**
I wish to enter in the app and navigate it

**Comment by nekramste** [comment]
Fixed [Commit](https://github.com/IDMONEY/MoneyMakingWalletBK/commit/7d0104418ca15bb7d21134bb3e318f3e955e66bc)

**Comment by nekramste** [comment]
Closing this issue
